/*
 * @lc app=leetcode id=389 lang=golang
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (54.93%)
 * Likes:    843
 * Dislikes: 285
 * Total Accepted:    201K
 * Total Submissions: 363.5K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */

// @lc code=start
func findTheDifference(s string, t string) byte {
	return findTheDifference2(s, t)
}

// https://leetcode.com/problems/find-the-difference/discuss/593690/XOR-golang-solution
// XOR solution
func findTheDifference2(s string, t string) byte {
	var res byte
	for _, v := range []byte(s + t) {
		res ^= v
	}
	return res
}

func findTheDifference1(s string, t string) byte {
	hash := map[byte]int{}
	for _, v := range s {
		hash[byte(v)]++
	}

	for _, v := range t {
		if k, ok := hash[byte(v)]; ok && k > 0 {
			hash[byte(v)]--
		} else {
			return byte(v)
		}
	}
	return 0
}

// @lc code=end